### ISSUE TITLE
增值税有些特殊的并未考虑到 例如增值税普票  144031539110 

### ISSUE THREAD

**Issue by zgrjhwei** [fdstar/NumberValidators#2]

**Comment by fdstar** [comment]
144031539110 这是区块链发票，这个是支持的
然后因为我不做税务方面软件已经2年半了，所以对区块链后续的发展不是很了解，但以前区块链是只支持普票的，设计上为了区分开国家定义的12位普票和深圳的区块链发票，所以特意将结果展示为区块链的
